server.port=8182
spring.application.name=work-management

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=*******
spring.datasource.password=****

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.work.domain
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.com.work=debug

jwt.secret=change_this_to_long_random_secret_key_very_important
jwt.expiration=3600000

spring.jackson.time-zone=Asia/Seoul
